### ISSUE TITLE
Not working with newer OCaml versions

### ISSUE THREAD

**Issue by Heizmann** [rbonichon/smtpp#5]
using 6e0750087e5dc494519ccec24f419f856c754db2
running ``autoconf && ./configure``
got ``checking version of OCaml... configure: error: "Please use at least 4.02.1 (found 4.04.0)."``

**Comment by rbonichon** [comment]
@Heizmann This should be fixed in commit 57eb74bccbb0f30293ee058ded4b01baa1067756

Thanks for the wake-up call.

**Comment by Heizmann** [comment]
Thanks. Now I was able to compile smtpp according to the instructions given on the website.
